blog/core/views.py
####################################################
# IMPORTS (FROM LIBRARY) ###########################
####################################################

from flask import render_template, request, Blueprint, redirect, url_for, flash
from flask_login import current_user, login_required

####################################################
# IMPORTS (LOCAL) ##################################
####################################################

from blog.core.forms import Search_Form
from blog.core.search_engine import search
from blog.models import BlogPost, Notifications, View
from blog import db

####################################################
# BLUEPRINT SETUP ##################################
####################################################

core = Blueprint('core', __name__)

####################################################
# INDEX SETUP ######################################
####################################################

@core.route('/', methods=["GET", "POST"])
def index():
    View.delete_expired()
    Notifications.delete_expired()
    
    page = request.args.get('page', 1, type=int)

    blog_posts = BlogPost.query.order_by(BlogPost.views.desc(), BlogPost.date.desc()).paginate(page=page, per_page=6)
    if (current_user.is_authenticated):
        ids = db.engine.execute(f'select blog_id        \
                                  from View             \
                                  where user_id={current_user.id}')
        viewed = [id_blog[0] for id_blog in ids]
        categories = [current_user.last_viewed_catagory1, current_user.last_viewed_catagory2, current_user.last_viewed_catagory3]
        recommended = BlogPost.query.filter(BlogPost.category.in_(categories), BlogPost.author!=current_user, ~(BlogPost.id.in_(viewed))).order_by(BlogPost.views.desc(), BlogPost.date.desc()).paginate(page=page, per_page=3, error_out=False)
    else:
        recommended = None
    
    if (current_user.is_authenticated):
        notifs = Notifications.query.filter_by(user_id=current_user.id).order_by(Notifications.date.desc()).all()
    else:
        notifs = []

    form = Search_Form()

    if form.validate_on_submit():
        return redirect(url_for('core.search_page', param=form.param.data))

    return render_template('index.html', page_name="Home", blog_posts=blog_posts, recommended=recommended, notifs=notifs, form=form)

####################################################
# ABOUT SETUP ######################################
####################################################

@core.route('/about')
def about():
    if (current_user.is_authenticated):
        notifs = Notifications.query.filter_by(user_id=current_user.id).order_by(Notifications.date.desc()).all()
    else:
        notifs = []
    
    return render_template('about.html', notifs=notifs)

####################################################
# SEARCH SETUP #####################################
####################################################

@core.route('/search/<string:param>', methods=["GET", "POST"])
def search_page(param):
    users, blogs = search(param)
    
    if (current_user.is_authenticated):
        notifs = Notifications.query.filter_by(user_id=current_user.id).order_by(Notifications.date.desc()).all()
    else:
        notifs = []

    form = Search_Form()

    if form.validate_on_submit():
        return redirect(url_for('core.search_page', param=form.param.data))
    
    if ((not blogs) and users):
        open_tab = 2
    else:
        open_tab = 1
    
    return render_template('search.html', notifs=notifs, param=param, users=users, blogs=blogs, form=form, open_tab=open_tab)

####################################################
# INDEX (SORTED) SETUP #############################
####################################################

@core.route('/sorted', methods=["GET", "POST"])
def index_sorted():
    View.delete_expired()
    Notifications.delete_expired()
    
    page = request.args.get('page', 1, type=int)
    category_val = request.args.get('sort_val')
    
    if (not category_val):
        flash('Select a Category to sort by')
        return redirect(url_for('core.index'))

    if (category_val == "Alphabetically Asc"):
        blog_posts = BlogPost.query.order_by(BlogPost.title.asc()).paginate(page=page, per_page=6)
    elif (category_val == "Alphabetically Dsc"):
        blog_posts = BlogPost.query.order_by(BlogPost.title.desc()).paginate(page=page, per_page=6)
    elif (category_val == "Category"):
        blog_posts = BlogPost.query.order_by(BlogPost.category.asc()).paginate(page=page, per_page=6)
    elif (category_val == "By Date Asc"):
        blog_posts = BlogPost.query.order_by(BlogPost.date.asc()).paginate(page=page, per_page=6)
    elif (category_val == "By Date Dsc"):
        blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=6)
    else:
        blog_posts = BlogPost.query.order_by(BlogPost.views.desc()).paginate(page=page, per_page=6)

    if (current_user.is_authenticated):
        ids = db.engine.execute(f'select blog_id        \
                                  from View             \
                                  where user_id={current_user.id}')
        viewed = [id_blog[0] for id_blog in ids]
        categories = [current_user.last_viewed_catagory1, current_user.last_viewed_catagory2, current_user.last_viewed_catagory3]
        recommended = BlogPost.query.filter(BlogPost.category.in_(categories), BlogPost.author!=current_user, ~(BlogPost.id.in_(viewed))).order_by(BlogPost.views.desc(), BlogPost.date.desc()).paginate(page=page, per_page=3, error_out=False)
    else:
        recommended = None
    
    if (current_user.is_authenticated):
        notifs = Notifications.query.filter_by(user_id=current_user.id).order_by(Notifications.date.desc()).all()
    else:
        notifs = []

    form = Search_Form()

    if form.validate_on_submit():
        return redirect(url_for('core.search_page', param=form.param.data))

    return render_template('sorted.html', page_name="Home", blog_posts=blog_posts, recommended=recommended, notifs=notifs, form=form, category_val=category_val)

blog/post/views.py
####################################################
# IMPORTS (FROM LIBRARY) ###########################
####################################################

from flask import render_template, url_for, request, redirect, Blueprint, flash, abort
from flask_login import current_user, login_required

####################################################
# IMPORTS (LOCAL) ##################################
####################################################

from blog import db
from blog.models import BlogPost, User, Notifications, Followers, View, Likes, Comments
from blog.post.forms import BlogPostForm, CommentForm

####################################################
# BLUEPRINT SETUP ##################################
####################################################

blog_posts = Blueprint('blog_posts', __name__)

####################################################
# CREATE POST SETUP ################################
####################################################

@blog_posts.route('/create', methods=["GET", "POST"])
@login_required
def create_post():
    form = BlogPostForm()
    
    if (form.validate_on_submit() or request.method == "POST"):
        post = BlogPost(title=form.title.data, category=form.category.data, text=form.text.data, user_id=current_user.id)
        db.session.add(post)
        db.session.commit()

        followers = Followers.query.filter_by(followed_id=current_user.id).all()

        for follower in followers:
            notif = Notifications(follower.follower_id, f'{current_user.username} has posted a blog "{form.title.data}"!', post.id, True)
            db.session.add(notif)

        db.session.add(post)
        db.session.commit()

        flash('Post Created!')
        
        return redirect(url_for('core.index'))

    if (current_user.is_authenticated):
        notifs = Notifications.query.filter_by(user_id=current_user.id).order_by(Notifications.date.desc()).all()
    else:
        notifs = []

    return render_template('create_post.html', form=form, notifs=notifs)

####################################################
# BLOG POST VIEW SETUP #############################
####################################################

@blog_posts.route('/blog/<int:blog_post_id>', methods=["GET", "POST"])
def blog_post(blog_post_id):
    post = BlogPost.query.get_or_404(blog_post_id)
    form = CommentForm()

    previous_comments = Comments.query.filter_by(blog_id=post.id).order_by(Comments.date.desc()).all()

    if (form.validate_on_submit() or request.method == "POST"):
        comment = Comments(blog_post_id, current_user.id, form.text.data)
        db.session.add(comment)

        if (current_user.id != post.author.id):
            notif = Notifications(post.author.id, f'{current_user.username} has commented on your blog "{post.title}"!', post.id, True)
            db.session.add(notif)

        db.session.commit()
        
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post_id))

    if (current_user.is_authenticated and current_user.email != post.author.email):
        user = User.query.get_or_404(current_user.id)
        user.last_viewed_catagory3 = user.last_viewed_catagory2
        user.last_viewed_catagory2 = user.last_viewed_catagory1
        user.last_viewed_catagory1 = post.category
        
        db.session.commit()

        view = View.query.filter_by(user_id=current_user.id, blog_id=blog_post_id).first()

        if (not view):
            post.views += 1
            view = View(current_user.id, blog_post_id)
            db.session.add(view)
            db.session.commit()
    
    if (current_user.is_authenticated):
        notifs = Notifications.query.filter_by(user_id=current_user.id).order_by(Notifications.date.desc()).all()
    else:
        notifs = []
    
    if (current_user.is_authenticated):
        like_stat = Likes.query.filter_by(user_id=current_user.id, blog_id=blog_post_id).first()
    else:
        like_stat = None

    like_count = db.engine.execute(f'''
        select count(*)
        from Likes
        where blog_id={blog_post_id} and like={1}
    ''')
    dislike_count = db.engine.execute(f'''
        select count(*)
        from Likes
        where blog_id={blog_post_id} and like={0}
    ''')
    like_count = [res[0] for res in like_count][0]
    dislike_count = [res[0] for res in dislike_count][0]
    
    if (like_count == None):
        like_count = 0
    if (dislike_count == None):
        like_count = 0
    
    if (like_stat):
        like_val = like_stat.like
    else:
        like_val = None
    
    return render_template('blog_posts.html', title=post.title, date=post.date, post=post, category=post.category, notifs=notifs, like_val=like_val, like_count=like_count, dislike_count=dislike_count, previous_comments=previous_comments, form=form, User=User)

####################################################
# UPDATE POST SETUP ################################
####################################################

@blog_posts.route('/<int:blog_post_id>/update', methods=["GET", "POST"])
@login_required
def update(blog_post_id):
    blog_title = None
    post = BlogPost.query.get_or_404(blog_post_id)

    if (post.author != current_user):
        abort(403)
    
    form = BlogPostForm()
    
    if (form.validate_on_submit() or request.method == "POST"):
        post.title = form.title.data
        post.text= form.text.data
        post.category = form.category.data

        followers = Followers.query.filter_by(followed_id=current_user.id).all()

        for follower in followers:
            notif = Notifications(follower.follower_id, f'{current_user.username} has updated the blog "{blog_title}"!', post.id, True)
            db.session.add(notif)

        db.session.commit()
        flash('Updated Post!')
        return redirect(url_for('blog_posts.blog_post', blog_post_id=post.id))

    if (request.method == "GET"):
        form.title.data = post.title
        blog_title = post.title
        form.text.data = post.text
        form.category.data = post.category
    
    if (current_user.is_authenticated):
        notifs = Notifications.query.filter_by(user_id=current_user.id).order_by(Notifications.date.desc()).all()
    else:
        notifs = []

    return render_template('create_post.html', form=form, notifs=notifs)

####################################################
# DELETE POST SETUP ################################
####################################################

@blog_posts.route('/<int:blog_post_id>/delete', methods=["GET", "POST"])
@login_required
def delete(blog_post_id):
    post = BlogPost.query.get_or_404(blog_post_id)

    if (post.author != current_user):
        abort(403)
    
    followers = Followers.query.filter_by(followed_id=current_user.id).all()

    for follower in followers:
        notif = Notifications(follower.follower_id, f'{current_user.username} has deleted the blog "{post.title}"!', post.author.id, False)
        db.session.add(notif)
    
    db.session.delete(post)
    db.session.commit()

    flash('Blog Deleted!')

    return redirect(url_for('core.index'))

####################################################
# LIKE INTERACTION SETUP ###########################
####################################################

@blog_posts.route('/<int:user_id>/<int:blog_post_id>/<int:like>')
@login_required
def like(user_id, blog_post_id, like):
    post = BlogPost.query.get_or_404(blog_post_id)

    if (not current_user.is_authenticated or post.user_id == current_user.id):
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post_id))

    like_entry = Likes.query.filter_by(user_id=user_id, blog_id=blog_post_id).first()

    blog = BlogPost.query.get_or_404(blog_post_id)
    user = User.query.get_or_404(blog.author.id)
    user_reaction = User.query.get_or_404(user_id)

    if (not like_entry):
        like_entry = Likes(user_id, blog_post_id, bool(like))
        db.session.add(like_entry)

        notif = Notifications(user.id, f'{user_reaction.username} has reacted to your blog "{blog.title}"!', blog_post_id, True)
        db.session.add(notif)

    else:
        if (like_entry.like != bool(like)):
            like_entry.like = bool(like)

            notif = Notifications(user.id, f'{user_reaction.username} has reacted to your blog "{blog.title}"!', blog_post_id, True)
            db.session.add(notif)

        else:
            db.session.delete(like_entry)

    db.session.commit()
    
    return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post_id))

####################################################
# EDIT COMMENT SETUP ###############################
####################################################

@blog_posts.route('/<int:comment_id>/edit', methods=["GET", "POST"])
@login_required
def edit_comment(comment_id):
    comment = Comments.query.get_or_404(comment_id)

    if (comment.user_id != current_user.id):
        abort(403)
    
    form = CommentForm()
    
    if (form.validate_on_submit() or request.method == "POST"):
        comment.text = form.text.data
        db.session.commit()

        flash('Comment Updated!')
        return redirect(url_for('blog_posts.blog_post', blog_post_id=comment.blog_id))

    if (request.method == "GET"):
        form.text.data = comment.text
    
    if (current_user.is_authenticated):
        notifs = Notifications.query.filter_by(user_id=current_user.id).order_by(Notifications.date.desc()).all()
    else:
        notifs = []

    return render_template('edit_comment.html', form=form, notifs=notifs)

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="shortcut icon" href="{{url_for('static', filename='img/favicon.ico')}}" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='style/base_style.css')}}"> {% block links %} {% endblock links %}
</head>

<body style="width: 100vw; overflow-x: hidden !important; overflow-y: scroll;">
    <div class="background" style="background-image: linear-gradient(rgba(0,0,0,0.05), rgba(0,0,0,0.05)), url({{url_for('static', filename='img/background_img/1.jpg')}});"></div>
    <div class="background" style="background-image: linear-gradient(rgba(0,0,0,0.05), rgba(0,0,0,0.05)), url({{url_for('static', filename='img/background_img/2.jpg')}});"></div>
    <div class="background" style="background-image: linear-gradient(rgba(0,0,0,0.05), rgba(0,0,0,0.05)), url({{url_for('static', filename='img/background_img/3.jpg')}});"></div>
    <div class="background" style="background-image: linear-gradient(rgba(0,0,0,0.05), rgba(0,0,0,0.05)), url({{url_for('static', filename='img/background_img/4.jpg')}});"></div>
    <div class="background" style="background-image: linear-gradient(rgba(0,0,0,0.05), rgba(0,0,0,0.05)), url({{url_for('static', filename='img/background_img/5.png')}});"></div>
    <div class="background" style="background-image: linear-gradient(rgba(0,0,0,0.05), rgba(0,0,0,0.05)), url({{url_for('static', filename='img/background_img/6.png')}});"></div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="position: fixed; top: 0; left: 0; width: 103vw; background-color: #151D33 !important; z-index: 9999;">
        <div class="container">
            <a class="navbar-brand nav-link-mod" href="{{url_for('core.index')}}">
                <h4 class="home-link">Blog Tap</h4>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link nav-link-mod" href="{{url_for('blog_posts.create_post')}}">Create Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-mod" href="{{url_for('user.account')}}">Account</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link nav-link-mod" href="{{url_for('user.login')}}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-mod" href="{{url_for('user.register')}}">Register</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link nav-link-mod" href="{{url_for('core.about')}}">About</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link nav-link-mod" type="button" name="button" data-toggle="modal" data-target="#logout_modal">Log Out</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle nav-link-mod" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: max-content;">
                            <i class="fa fa-bell-o" aria-hidden="true"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="max-height: 200px; max-width: 90vw; overflow-y: scroll;">
                            {% if notifs %} {% for mess in notifs %} {% if mess.is_blog %}
                            <a class="dropdown-item text-break text-normal-media-small" href="{{url_for('blog_posts.blog_post', blog_post_id=mess.link_id)}}">
                                <strong class="text-muted" style="font-size: small; font-weight: 400;">{{mess.date.strftime("%d/%m/%Y")}}: </strong> {{mess.text}}
                            </a>
                            {% else %}
                            <a class="dropdown-item text-break text-normal-media-small" href="{{url_for('user.user_posts', user_id=mess.link_id)}}">
                                <strong class="text-muted" style="font-size: small; font-weight: 400;">{{mess.date.strftime("%d/%m/%Y")}}: </strong> {{mess.text}}
                            </a>
                            {% endif %} {% endfor %} {% else %}
                            <p class="dropdown-item text-normal-media-small">You Don't have any Notification</p>
                            {% endif %}
                        </div>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% for mess in get_flashed_messages() %}
    <div class="alert alert-primary alert-dismissible fade show" role="alert" style="z-index: 100000; position: fixed; top: 0; width: 100vw;">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button> {{ mess }}
    </div>
    {% endfor %}

    <div style="height: 128px;"></div>
    <div class="container">
        {% block content %} {% endblock content %}
    </div>

    <div class="modal" tabindex="-1" role="dialog" id="logout_modal" style="z-index: 100000; top: 25%; max-width: 99vw;">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Log Out</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to log out?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-cancel" data-dismiss="modal">Cancel</button>
                    <a href="{{url_for('user.logout')}}">
                        <input type="submit" class="btn-danger-imp" value="Logout">
                    </a>
                </div>
            </div>
        </div>
    </div>

    {% if not current_user.is_authenticated %}
    <div id="background-img-selector" class="1"></div>
    {% else %}
    <div id="background-img-selector" class="{{current_user.background}}"></div>
    {% endif %}

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='script/background_pic.js')}}"></script>
    <script>
        setTimeout(function() {
            $('.alert-dismissible').remove();
        }, 3000);
    </script>
    {% block scripts %} {% endblock scripts %}
</body>

</html>

blog/templates/blog_posts.html
{% extends 'base.html' %} {% block title %} {{post.title}} {% endblock title %} {% block content %}

<div class="container">
    <div class="img-post" style="background-image: url({{url_for('static', filename='img/blog_background/'+post.category+'.jpg')}});"></div>
    <div style="position: relative; top: -2rem;">
        <h1 class="reactive-text-1">Title: {{post.title}}</h1>
        <h3 class="reactive-text-3">Author: <a href="{{url_for('user.user_posts', user_id=post.author.id)}}">{{post.author.username}}</a></h3>
        <h5 class="text-muted reactive-text-5">Published: {{post.date.strftime("%d %B %Y")}}</h5>
        <h5 class="text-muted reactive-text-5">Category: {{post.category}}</h5>
        <h5 class="reactive-text-5">Views: {{post.views}}</h5>
        {% if post.author == current_user or not current_user.is_authenticated %}
        <h5 class="reactive-text-5"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i>: {{like_count}}</h5>
        <h5 class="reactive-text-5"><i class="fa fa-thumbs-o-down" aria-hidden="true"></i>: {{dislike_count}}</h5>
        {% endif %}
        <br> {{post.text|markdown}} {% if post.author == current_user %}
        <br>
        <a href="{{url_for('blog_posts.update', blog_post_id=post.id)}}"> <button class="btn-normal">Edit</button></a>
        <button type="button" name="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button> {% else %} {% if current_user.is_authenticated %}

        <br><br>
        <h5 class="reactive-text-5">Did You Like The Blog?</h5>
        <a href="{{url_for('blog_posts.like', user_id=current_user.id, blog_post_id=post.id, like=1)}}" class="thumbs-up reactive-text-5" style="margin-right: 12px; margin-top: 12px; text-decoration: none;">
            {% if like_val %}
            <i class="fa fa-thumbs-up" aria-hidden="true"></i>    
            <span style="color: #151D33; transform: scale(1);">{{like_count}}</span>         
            {% else %}
            <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>   
            <span style="color: #151D33; transform: scale(1);">{{like_count}}</span>          
            {% endif %}
        </a>
        <a href="{{url_for('blog_posts.like', user_id=current_user.id, blog_post_id=post.id, like=0)}}" class="thumbs-up reactive-text-5" style="margin-right: 12px; margin-top: 12px; text-decoration: none;">
            {% if like_val == False %}
            <i class="fa fa-thumbs-down" aria-hidden="true"></i>  
            <span style="color: #151D33; transform: scale(1);">{{dislike_count}}</span>      
            {% else %}
            <i class="fa fa-thumbs-o-down" aria-hidden="true"></i> 
            <span style="color: #151D33; transform: scale(1);">{{dislike_count}}</span> 
            {% endif %}
        </a> {% endif %} {% endif %}

        <div class="container" style="background: rgba(0, 0, 0, 0.25); margin-top: 12px;">
            <br>
            <h4 class="reactive-text-3">Comments:</h4>
            <div style="width: 100%; height: 0.25px; background-color: #151D33;"></div>
            {% if previous_comments %} {% for comment in previous_comments %}
            <div class="comment">
                <p class="reactive-text-5" style="margin-bottom: 4px;">
                    {{comment.text|markdown}}
                </p>
                <p class="reactive-text-5" style="margin-bottom: 2px; color: rgb(80, 80, 80);">By:
                    <a href="{{url_for('user.user_posts', user_id=(User.query.get_or_404(comment.user_id)).id)}}">
                        {{(User.query.get_or_404(comment.user_id)).username}} 
                    </a> {% if (current_user.is_authenticated and (current_user.id == comment.user_id)) %}
                    <a href="{{url_for('blog_posts.edit_comment', comment_id=comment.id)}}" class="thumbs-up edit" style="margin-left: 8px;">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                    </a>
                    {% endif %}
                </p>
                <p class="reactive-text-5" style="color: rgb(80, 80, 80);">Posted On: {{comment.date.strftime("%d/%m/%Y")}}</p>
            </div>
            {% endfor %} {% else %}
            <div class="comment">
                <h3 class="reactive-text-3" style="margin-bottom: 64px; margin-top: 48px;">No comments have been posted for this blog</h3>
            </div>
            {% endif %}

            <div style="width: 100%; height: 0.25px; background-color: #151D33;"></div>

            <br><br> {% if current_user.is_authenticated %}
            <form method="post">
                {{form.hidden_tag()}} {{form.text.label(class='form-control-label text-normal-media-small')}}<br> {{form.text(placeholder="Write a Comment", class='form-control form-control-lg form-input-normal text-normal-media-small', style="border:
                none;", rows=6)}}
                <br>
                <div style="vertical-align: middle; margin-bottom: 24px;" class="text-normal-media-small">
                    <div style="display: inline-block; width: 25px; height: 25px; border-radius: 50%; border: 2px solid blue; color: blue; position: relative; top: 2px;" align='center'>
                        <strong style="position: relative; top: -2px; color: blue; font-size: medium;">i</strong>
                    </div>
                    <strong style="color: blue;">NOTE:</strong> You can use <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet"> Markdown </a> to add pictures or style your blog text
                </div>
                {{form.submit(class='text-normal-media-small')}}
            </form>
            {% endif %}
            <br>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="del_modal" style="z-index: 100000; top: 25%; max-width: 99vw;">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Post</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete the post</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-cancel" data-dismiss="modal">Cancel</button>

                <form action="{{url_for('blog_posts.delete', blog_post_id=post.id)}}" method="post">
                    <input type="submit" class="btn btn-danger" value="Delete">
                </form>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

blog/templates/forgot-pass.html
{% extends 'base.html' %} {% block title %} Forgot Password {% endblock title %} {% block content %}

<form method="POST">
    {{form.hidden_tag()}} {{form.email.label(class='label-text text-normal-media-small')}}
    <br> {{form.email(class='col-sm-4 text-normal-media-small', placeholder='Enter email-id')}}
    <br><br> {{form.submit(class='text-normal-media-small')}}
</form>

{% endblock content %}